---
engines:
  duplication:
    enabled: true
    config:
      languages: ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.rb"
  - "**.gemspec"
  - "bin/**"
  - "Rakefile"
  - "Gemfile"
exclude_paths:
- test/**/*
