language: ruby
sudo: false
rvm:
  - 2.0
  - 2.1
  - 2.2
  - ruby-head
  - jruby-9.0.3.0
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.0.3.0
before_install: gem install bundler
before_script: bundle update
