#!/usr/bin/env ruby

require 'io/console'

class BfInterpreter
  def initialize(allow_flow = true)
    @option = Hash.new
    @option['allow_flow'] = allow_flow
  end

  def wrap_around?
    @option['allow_flow']
  end

  def wrap_around=(allow_flow)
    @option['allow_flow'] = allow_flow
  end

  def run(src)
    units = []

    # construct units
    File.open(src) do |file|
      units = construct_program_units(file)
    end

    # match brackets
    match_brackets(units)

    # do interpret
    tape = Array.new
    cell = 0
    unit = units[0]
    while unit.has_next
      if tape[cell] == nil
        tape[cell] = BfCell.new(cell)
      end

      case unit.instruction
        when '+' then tape[cell].increase(1, @option['allow_flow'])
        when '-' then tape[cell].decrease(1, @option['allow_flow'])
        when '<' then
          cell -= 1
          fail 'Cell position out of bound!' if cell < 0
        when '>' then cell += 1
        when ',' then tape[cell].value = STDIN.getch
        when '.' then STDOUT.putc tape[cell].value
        when '[' then
          if tape[cell].value == 0
            unit = unit.match
            next
          end
        when ']' then
          if tape[cell].value != 0
            unit = unit.match
            next
          end
        else fail "Illegal instruction '#{c.chr}'!"
      end

      unit = unit.next
    end
  end

  private def construct_program_units(file)
    units = Array.new
    position = 0

    file.each_byte do |c|
      case c.chr
        when '+', '-', '<', '>', '[', ']', '.', ',' then
          unit = BfProgramUnit.new(c.chr)
          units[position - 1].next = unit if position > 0
          units[position] = unit
          position += 1
        else
          # other characters are considered as comments, do nothing
      end
    end

    units
  end

  private def match_brackets(units)
    units.each_index do |i|
      if units[i].instruction == '['
        level = 0
        units[i + 1 .. units.length - 1].each_index do |j|
          j += i + 1
          if units[j].instruction == '['
            level += 1
          elsif units[j].instruction == ']'
            if level > 0
              level -= 1
            else
              units[i].match = units[j]
              units[j].match = units[i]
              break
            end
          end
        end
        fail 'Unmatched brackets!' if level > 0
      end
    end
  end

  class BfCell
    attr_accessor :position, :value

    def initialize(position, value = 0)
      @position = position
      @value = value
    end

    def increase(increment = 1, allow_flow = true)
      if !allow_flow && (@value + increment < 0 || @value + increment > 255)
        fail 'Overflow or underflow happened while forbidden!'
      else
        @value = (@value + increment) % 256
      end
    end

    def decrease(decrement = 1, allow_flow = true)
      self.increase(-decrement, allow_flow)
    end
  end

  class BfProgramUnit
    attr_reader :instruction

    attr_accessor :match
    attr_accessor :next

    def initialize(instruction)
      @instruction = instruction
      @match = nil
      @next = nil
    end

    def has_next
      @next != nil
    end
  end
end

interpreter = BfInterpreter.new
interpreter.run(ARGV[0])
